# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 11:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import dormrent.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(editable=False, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('iconpic', models.ImageField(blank=True, null=True, upload_to=dormrent.models.icon_image_url)),
                ('address', models.CharField(default='KTU', max_length=255)),
                ('location2', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('mainphonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+90', max_length=128, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebooklink', models.URLField(blank=True, null=True)),
                ('officalweblink', models.URLField(blank=True, null=True)),
                ('pricelow', models.FloatField(blank=True, null=True)),
                ('pricehigh', models.FloatField(blank=True, null=True)),
                ('starlevel', models.FloatField(default=0)),
                ('thumbsup', models.PositiveIntegerField(default=0)),
                ('thumbsdown', models.PositiveIntegerField(default=0)),
                ('sharenumbers', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('m', 'Boy'), ('f', 'Girl'), ('mf', 'Both Girl and Boy'), ('n', 'Not Sure')], default='n', max_length=2)),
                ('numberOfPeoplePerRoom', models.CharField(blank=True, help_text='enter in this format: 1,2,3', max_length=50, null=True)),
                ('roomsperbath', models.FloatField(blank=True, editable=False, null=True)),
                ('numberofrooms', models.PositiveSmallIntegerField(blank=True, help_text='how many rooms do you have in total?', null=True)),
                ('numberofstudents', models.PositiveSmallIntegerField(blank=True, help_text='how many students can you host in total?', null=True)),
                ('allowcomments', models.BooleanField(default=True, help_text='allow to be commented or not?')),
            ],
            options={
                'ordering': ['-starlevel'],
            },
        ),
        migrations.CreateModel(
            name='ApartFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, help_text='1 is the highest (most important)')),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('room', 'oda'), ('floor', 'kat'), ('building', 'bina')], default='building', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dormrent.models.apart_image_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=dormrent.models.apart_image_path)),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormrent.Apart')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('numberOfPeoplePerRoom', models.PositiveSmallIntegerField(default=2)),
                ('restroomnumber', models.PositiveIntegerField(default=2)),
                ('restroomtype', models.CharField(choices=[('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=20)),
                ('showernumber', models.PositiveSmallIntegerField(default=1)),
                ('showertype', models.CharField(choices=[('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '3 to 6 rooms share'), ('5', '>6 rooms share')], default='3', max_length=20)),
                ('kitchen', models.CharField(choices=[('0', 'no kitchen'), ('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=20)),
                ('livingroom', models.CharField(choices=[('0', 'no livingroom'), ('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(editable=False, max_length=300, null=True)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormrent.University')),
            ],
        ),
        migrations.AddField(
            model_name='apart',
            name='apartfeatures',
            field=models.ManyToManyField(blank=True, to='dormrent.ApartFeatures'),
        ),
        migrations.AddField(
            model_name='apart',
            name='dislikedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='dislikedaparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='likedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='likedaparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='ownedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='roomtype',
            field=models.ManyToManyField(blank=True, null=True, to='dormrent.RoomType'),
        ),
        migrations.AddField(
            model_name='apart',
            name='sharedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='sharedaparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='visitedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='visitedaparts', to=settings.AUTH_USER_MODEL),
        ),
    ]
