# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('iconpic', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(default='KTU', max_length=255)),
                ('location2', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numberofrooms', models.PositiveSmallIntegerField(blank=True, help_text='how many rooms do you have in total?', null=True)),
                ('numberofstudents', models.PositiveSmallIntegerField(blank=True, help_text='how many students can you host in total?', null=True)),
                ('roomsperbath', models.PositiveSmallIntegerField(default=3, help_text='how many rooms share on bathroom?')),
                ('facebooklink', models.URLField(blank=True, null=True)),
                ('officalweblink', models.URLField(blank=True, null=True)),
                ('starlevel', models.FloatField()),
                ('allowcomments', models.BooleanField(default=True, help_text='allow to be commented or not?')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starlevel', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('body', models.TextField(blank=True, null=True)),
                ('likelevel', models.PositiveSmallIntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
