# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170817_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='apartment',
            new_name='apart',
        ),
    ]
