# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_freqentlyaskedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreqentlyAskedQuestions',
            new_name='FrequentlyAskedQuestions',
        ),
    ]
