# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170914_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='sharenumbers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apart',
            name='thumbsdown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apart',
            name='thumbsup',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
