# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170817_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University')),
            ],
        ),
        migrations.AlterField(
            model_name='apart',
            name='slug',
            field=models.CharField(editable=False, max_length=300),
        ),
    ]
