# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170818_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartimage/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='apart',
            name='gender',
            field=models.CharField(choices=[('m', 'Erkek'), ('f', 'Kiz'), ('mf', 'Erkek and Kiz'), ('n', 'Not Sure')], default='n', max_length=2),
        ),
        migrations.AddField(
            model_name='apartimage',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apart'),
        ),
    ]
