# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20170915_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='dislikedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='dislikedaparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='likedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='likedaparts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apart',
            name='sharedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='sharedaparts', to=settings.AUTH_USER_MODEL),
        ),
    ]
