# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_apart_ownedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='visitedby',
            field=models.ManyToManyField(blank=True, editable=False, related_name='visitedaparts', to=settings.AUTH_USER_MODEL),
        ),
    ]
