# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170818_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apart',
            name='numberOfPeoplePerRoom',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='apartimage/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likenumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apart',
            name='apartfeatures',
            field=models.ManyToManyField(to='main.ApartFeatures'),
        ),
    ]
