# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170822_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartfeatures',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartfeatures',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, help_text='1 is the highest (most important)'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='numberOfPeoplePerRoom',
            field=models.CharField(blank=True, help_text='enter in this format: 1,2,3', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apart',
            name='roomsperbath',
            field=models.CharField(blank=True, help_text='how many rooms share one bathroom?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='apartimage/%Y/%m/%d'),
        ),
    ]
