# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_apart_visitedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='apart',
            name='gender',
            field=models.CharField(choices=[('m', 'Boy'), ('f', 'Girl'), ('mf', 'Both Girl and Boy'), ('n', 'Not Sure')], default='n', max_length=2),
        ),
    ]
