# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170822_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartfeatures',
            name='category',
            field=models.CharField(choices=[('room', 'oda'), ('floor', 'kat'), ('building', 'bina')], default='building', max_length=10),
        ),
        migrations.AlterField(
            model_name='apart',
            name='apartfeatures',
            field=models.ManyToManyField(blank=True, to='main.ApartFeatures'),
        ),
    ]
