# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170824_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apart',
            name='starlevel',
            field=models.FloatField(default=0.0),
        ),
    ]
