# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170825_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('numberOfPeoplePerRoom', models.PositiveSmallIntegerField(default=2)),
                ('restroomnumber', models.PositiveIntegerField(default=2)),
                ('restroomtype', models.CharField(choices=[('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=20)),
                ('showernumber', models.PositiveSmallIntegerField(default=1)),
                ('showertype', models.CharField(choices=[('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '3 to 6 rooms share'), ('5', '>6 rooms share')], default='3', max_length=20)),
                ('kitchen', models.CharField(choices=[('0', 'no kitchen'), ('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=20)),
                ('livingroom', models.CharField(choices=[('0', 'no livingroom'), ('1', 'In room'), ('2', '2 rooms share'), ('3', '3 rooms share'), ('4', '> 3 rooms share')], default='3', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='apart',
            name='roomsperbath',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='apart',
            name='roomtype',
            field=models.ManyToManyField(blank=True, null=True, to='main.RoomType'),
        ),
    ]
